# Generated by Django 2.2.1 on 2019-06-14 07:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('TakeTestApp', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tests',
            name='test_file',
            field=models.FileField(upload_to='uploads/TestDocument_<django.db.models.query_utils.DeferredAttribute object at 0x1023af048>_2019-06-14 07:01:41.303174.json'),
        ),
    ]
