# Generated by Django 2.2.1 on 2019-06-14 07:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('TakeTestApp', '0002_auto_20190614_0701'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tests',
            name='test_file',
            field=models.FileField(upload_to='uploads/'),
        ),
    ]
