# Generated by Django 2.2.1 on 2019-06-25 06:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('TakeTestApp', '0003_auto_20190614_0705'),
    ]

    operations = [
        migrations.AddField(
            model_name='tests',
            name='exam_duration',
            field=models.IntegerField(default=60),
        ),
    ]
