# Generated by Django 2.2.1 on 2019-06-25 18:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('TakeTestApp', '0005_results'),
    ]

    operations = [
        migrations.RenameField(
            model_name='results',
            old_name='test_id',
            new_name='test',
        ),
    ]
