# Generated by Django 2.2.1 on 2019-06-26 11:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('TakeTestApp', '0006_auto_20190625_1813'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='results',
            unique_together={('user', 'test')},
        ),
    ]
