# Generated by Django 2.2.1 on 2019-06-26 12:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('TakeTestApp', '0007_auto_20190626_1151'),
    ]

    operations = [
        migrations.AddField(
            model_name='tests',
            name='url',
            field=models.URLField(blank=True, null=True),
        ),
    ]
